### Aula 2 - Como começar um projeto com Pandas +
### Aula 03 - Importação de dados no Pandas + DataFrames e Series

In [2]:
import pandas as pd

#### Dataframe

In [3]:
diretorio_apple = "../data/apple_products_pricing_2020_2026.csv"
diretorio_student = "../data/student_burnout_dropout_dataset_2.csv"

df_apple = pd.read_csv(diretorio_apple)
df_apple

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

#### Series

In [15]:
type(df_apple)

pandas.DataFrame

In [18]:
type(df_apple["Platform"])

pandas.Series

### Aula 04 - Conhecendo um DataFrame: Aprendendo a fazer perguntas

#### Aprendendo a perguntar

In [26]:
df_apple.head()

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35

In [ ]:
df_apple.tail()

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [25]:
df_apple.shape

(80000, 14)

In [28]:
df_apple.columns

Index(['Date', 'Platform', 'Product_Category', 'Model_Name', 'Condition',
       'Launch_Price_USD', 'Launch_Price_INR', 'Current_Price_USD',
       'Current_Price_INR', 'Discount_Pct', 'Sale_Event', 'Stock_Status',
       'Rating', 'Reviews_Count'],
      dtype='str')

In [30]:
df_apple.info()

<class 'pandas.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               80000 non-null  str
 1   Platform           80000 non-null  str
 2   Product_Category   80000 non-null  str
 3   Model_Name         80000 non-null  str
 4   Condition          80000 non-null  str
 5   Launch_Price_USD   80000 non-null  int64
 6   Launch_Price_INR   80000 non-null  int64
 7   Current_Price_USD  80000 non-null  float64
 8   Current_Price_INR  80000 non-null  float64
 9   Discount_Pct       80000 non-null  float64
 10  Sale_Event         6649 non-null   str
 11  Stock_Status       80000 non-null  str
 12  Rating             80000 non-null  float64
 13  Reviews_Count      80000 non-null  int64
dtypes: float64(4), int64(3), str(7)
memory usage: 8.5 MB

In [33]:
df_apple.describe()

,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Rating,Reviews_Count
count,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000,80000.000000
mean,963.959125,94467.994250,782.769855,74628.342439,21.418826,4.450099,2405.995925
std,470.086413,46068.468464,461.673970,45117.872172,16.697310,0.269782,1973.630852
min,329.000000,32242.000000,109.930000,9157.680000,-2.000000,3.800000,10.000000
25%,599.000000,58702.000000,432.930000,41686.835000,6.700000,4.300000,896.000000
50%,799.000000,78302.000000,699.740000,67324.020000,21.300000,4.400000,1893.500000
75%,1199.000000,117502.000000,989.112500,96568.117500,36.800000,4.700000,3383.000000
max,1999.000000,195902.000000,2038.970000,203668.710000,73.100000,4.900000,11526.000000

In [34]:
df_apple["Platform"].describe()

count        80000
unique           2
top       Flipkart
freq         40043
Name: Platform, dtype: object

In [35]:
df_apple.dtypes

Date                     str
Platform                 str
Product_Category         str
Model_Name               str
Condition                str
Launch_Price_USD       int64
Launch_Price_INR       int64
Current_Price_USD    float64
Current_Price_INR    float64
Discount_Pct         float64
Sale_Event               str
Stock_Status             str
Rating               float64
Reviews_Count          int64
dtype: object

In [37]:
df_apple.sample(5)

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
35831,2024-10-14,Amazon,iPhone,iPhone 15 128GB,New,799,78302,534.21,52461.13,33.1,Great Indian Festival,In Stock,4.8,1017
70644,2026-03-24,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,685.97,58022.59,19.2,NaN,In Stock,3.8,711
66696,2026-01-27,Amazon,iPhone,iPhone 13 Pro Max 256GB,Renewed/Refurbished,1199,117502,605.12,51262.44,49.5,NaN,Out of Stock,4.0,2611
65095,2026-01-05,Amazon,iPhone,iPhone 15 Pro Max 256GB,New,1199,117502,980.95,95973.86,18.2,NaN,In Stock,4.3,2024
19964,2023-11-02,Flipkart,iPad,iPad Air (5th Gen) 64GB,Renewed/Refurbished,599,58702,418.48,35864.94,30.1,NaN,In Stock,3.9,1532

In [38]:
df_apple.index

RangeIndex(start=0, stop=80000, step=1)

In [45]:
df_apple.nunique()

Date                  2130
Platform                 2
Product_Category         4
Model_Name              31
Condition                2
Launch_Price_USD         9
Launch_Price_INR         9
Current_Price_USD    49611
Current_Price_INR    79626
Discount_Pct           695
Sale_Event               4
Stock_Status             3
Rating                  12
Reviews_Count         8698
dtype: int64

In [47]:
df_apple.isnull().sum()

Date                     0
Platform                 0
Product_Category         0
Model_Name               0
Condition                0
Launch_Price_USD         0
Launch_Price_INR         0
Current_Price_USD        0
Current_Price_INR        0
Discount_Pct             0
Sale_Event           73351
Stock_Status             0
Rating                   0
Reviews_Count            0
dtype: int64

In [49]:
df_apple.memory_usage().sum()

np.int64(8960132)

In [51]:
len(df_apple)

80000